language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  npm: false
  directories:
     - ./node_modules

before_install:
  - cd BiCo

install:
  - npm install

script:
- npm run build
- npm run test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadless
- npm run test-with-coverage
